repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.1.0
  hooks:
    - id: black
      language_version: python3.13
      exclude: ^raspiboard/canids\.py$

- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/PyCQA/flake8
  rev: 7.2.0
  hooks:
    - id: flake8
      args:
      - --max-line-length=88  # Black compatibility
      - --extend-ignore=E203,E701,E501  # Black compatibility, and my preferences