#!/bin/bash

SCRIPT_DIR=$(dirname "$0")

HEADER_FILE="$SCRIPT_DIR/common/can_identifiers.hpp"
PYTHON_AUTOGENERATED_FILE="$SCRIPT_DIR/raspiboard/robot/canids.py"

if [ "$HEADER_FILE" -nt "$PYTHON_AUTOGENERATED_FILE" ]; then
    echo "$HEADER_FILE is more recent than $PYTHON_AUTOGENERATED_FILE. Regenerating canid.py..."
    python3 generate_can_identifiers.py
else
    echo "$PYTHON_AUTOGENERATED_FILE is up to date. No need to regenerate."
fi

rsync --archive --verbose --delete --executability --exclude='__pycache__/' "$SCRIPT_DIR/raspiboard/" pi@192.168.0.14:/home/pi/MonobotSoftware/