#!/bin/bash

HEADER_FILE="common/can_identifiers.hpp"
PYTHON_AUTOGENERATED_FILE="raspiboard/canids.py"

if [ "$HEADER_FILE" -nt "$PYTHON_AUTOGENERATED_FILE" ]; then
    echo "$HEADER_FILE is more recent than $PYTHON_AUTOGENERATED_FILE. Regenerating canid.py..."
    python3 generate_can_identifiers.py
else
    echo "$PYTHON_AUTOGENERATED_FILE is up to date. No need to regenerate."
fi

rsync --archive --verbose --delete --executability --exclude='__pycache__/' raspiboard pi@192.168.0.14:/home/pi/VRAC/